(function(){
  const VERSION='v22.1.1';
  const manifest=window.CAMPING_MANIFEST||{states:[]};
  window.CAMPING_STATE_DATA=window.CAMPING_STATE_DATA||{};
  const STORAGE_KEYS={enabledStates:'campingMap.enabledStates.v2211',enabledLayers:'campingMap.enabledLayers.v2211',basemap:'campingMap.basemap.v2211',draftQueue:'campingMap.draftQueue.v2211'};
  const layerDefs=[{key:'federal-modern',label:'Federal · Modern',css:'pin-federal-modern'},{key:'federal-rustic',label:'Federal · Rustic',css:'pin-federal-rustic'},{key:'state-modern',label:'State · Modern',css:'pin-state-modern'},{key:'state-rustic',label:'State · Rustic',css:'pin-state-rustic'},{key:'local-modern',label:'Local · Modern',css:'pin-local-modern'},{key:'local-rustic',label:'Local · Rustic',css:'pin-local-rustic'},{key:'private-modern',label:'Private · Modern',css:'pin-private-modern'},{key:'private-rustic',label:'Private · Rustic',css:'pin-private-rustic'},{key:'boondocking',label:'Boondocking / dispersed',css:'pin-boondocking'},{key:'info',label:'Info / reference',css:'pin-info'}];
  const groupKeys={rustic:['federal-rustic','state-rustic','local-rustic','private-rustic','boondocking'],modern:['federal-modern','state-modern','local-modern','private-modern']};
  const app={map:null,markerGroup:null,oppLayer:null,draftMarker:null,locateMarker:null,baseLayerDefs:{},activeBaseLayers:[],enabledStates:normalizeEnabledStates(loadStoredArray(STORAGE_KEYS.enabledStates, ['MI'])),enabledLayers:new Set(loadStoredArray(STORAGE_KEYS.enabledLayers, layerDefs.map(d=>d.key))),showOpp:false,loadedStates:new Set(),statePromises:{},allSelectedSites:[],visibleSites:[],didInitialFit:false,basemapKey:localStorage.getItem(STORAGE_KEYS.basemap)||'topo',draftQueue:loadStoredArray(STORAGE_KEYS.draftQueue,[]),draftPoint:null,oppData:null,lastRenderInfo:{markers:0,multiplier:1,zoom:0,grid:0}};
  const els={version:gid('versionTag'),menuToggle:gid('menuToggle'),sidebar:gid('sidebar'),closeSidebar:gid('closeSidebar'),statusLine:gid('statusLine'),stateSelect:gid('stateSelect'),stateSelectMeta:gid('stateSelectMeta'),layerList:gid('layerList'),layerQuickFilters:gid('layerQuickFilters'),layerMenuSummary:gid('layerMenuSummary'),layerMenuButton:gid('layerMenuButton'),layerMenuPanel:gid('layerMenuPanel'),basemapSelect:gid('basemapSelect'),searchInput:gid('searchInput'),searchBtn:gid('searchBtn'),searchResults:gid('searchResults'),dataStats:gid('dataStats'),statusBar:gid('statusBar'),mapLoading:gid('mapLoading'),mapReadout:gid('mapReadout'),addMode:gid('addMode'),draftCoords:gid('draftCoords'),draftName:gid('draftName'),draftState:gid('draftState'),draftCategory:gid('draftCategory'),draftWebsite:gid('draftWebsite'),draftNotes:gid('draftNotes'),appendDraftBtn:gid('appendDraftBtn'),clearDraftBtn:gid('clearDraftBtn'),draftQueue:gid('draftQueue'),copyQueueBtn:gid('copyQueueBtn'),clearQueueBtn:gid('clearQueueBtn')};
  els.version.textContent=VERSION; els.draftQueue.value=app.draftQueue.join('\n'); els.basemapSelect.value=app.basemapKey;

  function failBoot(message){ try{els.statusLine.textContent=message||'Map failed to start.'; els.mapLoading.classList.add('hidden'); notify(message||'Map failed to start.',5000);}catch(e){console.error(e);} }
  if(window.addEventListener){ window.addEventListener('error',()=>failBoot('Map startup hit a script error.')); window.addEventListener('unhandledrejection',()=>failBoot('Map startup hit a loading error.')); }

  const svg={tent:'<svg viewBox="0 0 24 24"><path fill="currentColor" d="M3 18.5 10.8 5h2.4L21 18.5h-3.1l-5.1-9.1-2.9 4.9 1.9 4.2H9.2l-1.5-3.2-1.7 3.2H3Zm6.8 0h4.5l-2.2-5-2.3 5Z"/></svg>',tree:'<svg viewBox="0 0 24 24"><path fill="currentColor" d="m12 2 4 5h-2.1l3.6 4.5H15l3 3.8h-4.2V22h-3.6v-6.7H6l3-3.8H6.5L10.1 7H8L12 2Z"/></svg>',camper:'<svg viewBox="0 0 24 24"><path fill="currentColor" d="M4 8.5h10.6c.8 0 1.6.4 2.1 1l2.3 2.6H21a1 1 0 0 1 1 1v4.9h-1.7a2.6 2.6 0 0 1-5.1 0H9.8a2.6 2.6 0 0 1-5.1 0H3v-8.5a1 1 0 0 1 1-1Zm1.2 1.8v2.8H14v-2.8H5.2Zm11 3.1h3.2l-1.6-1.8a1.1 1.1 0 0 0-.8-.4h-.8v2.2ZM7.2 19a1.2 1.2 0 1 0 0-2.5 1.2 1.2 0 0 0 0 2.4Zm10.6 0a1.2 1.2 0 1 0 0-2.5 1.2 1.2 0 0 0 0 2.4Z"/></svg>',info:'<svg viewBox="0 0 24 24"><path fill="currentColor" d="M12 2.8A9.2 9.2 0 1 1 2.8 12 9.2 9.2 0 0 1 12 2.8Zm0 4a1.3 1.3 0 1 0 0 2.6 1.3 1.3 0 0 0 0-2.6Zm-1.7 5v1.8h1.1v3.6h-1.1V19h4.5v-1.8h-1.1v-5.4h-3.4Z"/></svg>',draft:'<svg viewBox="0 0 24 24"><path fill="currentColor" d="M4 17.5V20h2.5l8.6-8.6-2.5-2.5L4 17.5Zm12.4-9.9 1.5-1.5a1.2 1.2 0 0 1 1.7 0l.8.8a1.2 1.2 0 0 1 0 1.7l-1.5 1.5-2.5-2.5Z"/></svg>'};
  function gid(id){return document.getElementById(id)}
  function loadStoredArray(key,fallback){try{const raw=localStorage.getItem(key); if(!raw) return fallback.slice(); const parsed=JSON.parse(raw); return Array.isArray(parsed)?parsed:fallback.slice()}catch{return fallback.slice()}}
  function normalizeEnabledStates(arr){const valid=new Set(manifest.states.map(s=>s.code)); const picked=(Array.isArray(arr)?arr:[]).filter(code=>valid.has(code)); if(picked.length===1) return new Set(picked); if(picked.length===manifest.states.length) return new Set(picked); return new Set(valid.has('MI') ? ['MI'] : manifest.states.slice(0,1).map(s=>s.code))}
  function saveSet(key,setObj){localStorage.setItem(key,JSON.stringify(Array.from(setObj)))}
  function escapeHtml(str){return String(str||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function notify(msg,timeout=2800){els.statusBar.textContent=msg; els.statusBar.hidden=false; clearTimeout(notify._t); notify._t=setTimeout(()=>els.statusBar.hidden=true,timeout)}
  function buildStateSelect(){const sorted=manifest.states.slice().sort((a,b)=>a.name.localeCompare(b.name)); els.stateSelect.innerHTML=['<option value="__ALL__">All states loading</option>', ...sorted.map(s=>`<option value="${s.code}">${escapeHtml(s.name)} (${s.count})</option>`)].join(''); syncStateSelect()}
  function syncStateSelect(){const total=manifest.states.length; const size=app.enabledStates.size; if(size===1){const only=Array.from(app.enabledStates)[0]; els.stateSelect.value=only; const state=manifest.states.find(s=>s.code===only); els.stateSelectMeta.textContent=state?`${state.name} is the active dataset.`:'One state dataset is active.'; return;} els.stateSelect.value='__ALL__'; els.stateSelectMeta.textContent=`All ${total} state datasets are active.`}
  function buildLayerControls(){els.layerList.innerHTML=layerDefs.map(def=>`<label class="check small"><input type="checkbox" data-layer-toggle="${def.key}" ${app.enabledLayers.has(def.key)?'checked':''}><span class="legend-dot ${def.css}"></span><span>${escapeHtml(def.label)}</span></label>`).join(''); els.layerList.querySelectorAll('[data-layer-toggle]').forEach(i=>i.addEventListener('change',()=>{const k=i.getAttribute('data-layer-toggle'); i.checked?app.enabledLayers.add(k):app.enabledLayers.delete(k); saveSet(STORAGE_KEYS.enabledLayers,app.enabledLayers); syncQuickFilterButtons(); renderVisibleSites(false)})); syncQuickFilterButtons()}
  function updateLayerMenuSummary(){if(!els.layerMenuSummary) return; els.layerMenuSummary.textContent=`${app.enabledLayers.size} of ${layerDefs.length} on`;}
  function syncQuickFilterButtons(){els.layerQuickFilters.querySelectorAll('[data-layer-toggle-group]').forEach(btn=>{const name=btn.getAttribute('data-layer-toggle-group'); const keys=groupKeys[name]||[]; const allOn=keys.length && keys.every(k=>app.enabledLayers.has(k)); const anyOn=keys.some(k=>app.enabledLayers.has(k)); btn.classList.toggle('active', !!allOn); btn.classList.toggle('partial', !allOn && anyOn);}); updateLayerMenuSummary()}
  function toggleLayerGroup(name){const keys=groupKeys[name]; if(!keys) return; const allOn=keys.every(k=>app.enabledLayers.has(k)); keys.forEach(k=>{if(allOn) app.enabledLayers.delete(k); else app.enabledLayers.add(k)}); saveSet(STORAGE_KEYS.enabledLayers,app.enabledLayers); els.layerList.querySelectorAll('[data-layer-toggle]').forEach(i=>{i.checked=app.enabledLayers.has(i.getAttribute('data-layer-toggle'))}); syncQuickFilterButtons(); renderVisibleSites(false)}
  function makeTile(url,opts){return L.tileLayer(url,opts)}
  function initMap(){app.map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([44.9,-89.7],6); app.baseLayerDefs={'osm':[makeTile('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19, attribution:'&copy; OpenStreetMap contributors'})],'opentopo':[makeTile('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:20,maxNativeZoom:17, attribution:'&copy; OpenTopoMap, OpenStreetMap contributors'})],'topo':[makeTile('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19, attribution:'Tiles &copy; Esri'})],'satellite':[makeTile('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19, attribution:'Tiles &copy; Esri'})]}; setBasemap(app.basemapKey); app.markerGroup=L.layerGroup().addTo(app.map);  app.map.on('click',e=>{if(els.addMode.checked) setDraftPoint(e.latlng.lat,e.latlng.lng)})}
  function clearBaseLayers(){app.activeBaseLayers.forEach(layer=>{if(app.map.hasLayer(layer)) app.map.removeLayer(layer)}); app.activeBaseLayers=[]}
  function setBasemap(key){const chosen=app.baseLayerDefs[key]?key:'topo'; app.basemapKey=chosen; clearBaseLayers(); app.baseLayerDefs[chosen].forEach(layer=>{layer.addTo(app.map); app.activeBaseLayers.push(layer)}); els.basemapSelect.value=chosen; localStorage.setItem(STORAGE_KEYS.basemap,chosen)}
  function stateFileFor(code){const item=manifest.states.find(s=>s.code===code); return item?item.file:null}
  function loadState(code){if(window.CAMPING_STATE_DATA[code]){app.loadedStates.add(code); return Promise.resolve(window.CAMPING_STATE_DATA[code])} if(app.statePromises[code]) return app.statePromises[code]; const src=stateFileFor(code); if(!src) return Promise.reject(new Error('Missing state file for '+code)); const srcWithVersion=src + (src.includes('?')?'&':'?') + 'v=22.1.1'; app.statePromises[code]=new Promise((resolve,reject)=>{const script=document.createElement('script'); script.src=srcWithVersion; script.async=true; script.onload=()=>{app.loadedStates.add(code); resolve(window.CAMPING_STATE_DATA[code]||[])}; script.onerror=()=>reject(new Error('Could not load '+src)); document.head.appendChild(script)}); return app.statePromises[code]}
  async function loadOpportunityAreas(){try{const res=await fetch('data/opportunity-areas.geojson?v=21.1.4',{cache:'no-store'}); app.oppData=await res.json(); renderOppLayer()}catch(err){console.error(err); els.oppMeta.textContent='Opportunity-area file failed to load.'; notify('Opportunity-area file could not be loaded.',4000)}}
  function renderOppLayer(){app.oppLayer.clearLayers(); const featureCount=(app.oppData && Array.isArray(app.oppData.features))?app.oppData.features.length:0; els.oppMeta.textContent=featureCount?`${featureCount} opportunity area${featureCount===1?'':'s'} loaded.`:'No opportunity areas loaded.'; if(!app.showOpp || !featureCount) return; app.oppLayer.addData(app.oppData)}
  async function refreshData(){const selected=Array.from(app.enabledStates); syncStateSelect(); if(!selected.length){app.allSelectedSites=[]; renderVisibleSites(false); updateManifestStats(); return;} els.mapLoading.classList.remove('hidden'); els.statusLine.textContent='Loading state files…'; try{await Promise.all(selected.map(loadState)); app.allSelectedSites=selected.flatMap(code=>window.CAMPING_STATE_DATA[code]||[]); els.statusLine.textContent=`Loaded ${app.allSelectedSites.length} sites across ${selected.length} state file${selected.length===1?'':'s'}.`; renderVisibleSites(!app.didInitialFit); updateManifestStats()}catch(err){console.error(err); els.statusLine.textContent='One or more state files failed to load.'; notify('A state file failed to load. Check the browser console for details.',5000)}finally{els.mapLoading.classList.add('hidden')}}
  function updateManifestStats(){els.dataStats.textContent=`${app.enabledStates.size===manifest.states.length?'All':app.enabledStates.size} of ${manifest.states.length} state files enabled · ${app.allSelectedSites.length} records loaded.`}
  function siteLayerKey(site){if(site.layer==='boondocking'||site.layer==='info') return site.layer; return `${site.layer}-${site.subtype}`}
  function passesLayerFilter(site){return app.enabledLayers.has(siteLayerKey(site))}
  function markerClass(site){return {'federal-modern':'pin-federal-modern','federal-rustic':'pin-federal-rustic','state-modern':'pin-state-modern','state-rustic':'pin-state-rustic','local-modern':'pin-local-modern','local-rustic':'pin-local-rustic','private-modern':'pin-private-modern','private-rustic':'pin-private-rustic','boondocking':'pin-boondocking','info':'pin-info'}[siteLayerKey(site)]||'pin-info'}
  function iconFor(site){if(site.layer==='boondocking') return svg.tree; if(site.layer==='private') return svg.camper; if(site.layer==='info') return svg.info; return svg.tent}
  function subtypeLabel(site){if(site.layer==='boondocking') return 'Rustic by definition'; if(site.layer==='info') return 'Info / reference'; return `${site.layer.charAt(0).toUpperCase()+site.layer.slice(1)} ${site.subtype.charAt(0).toUpperCase()+site.subtype.slice(1)}`}
  function popupHtml(site){const nav=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(site.lat+','+site.lng)}`; const bits=[]; if(site.owner) bits.push(`<div><strong>Owner:</strong> ${escapeHtml(site.owner)}</div>`); if(site.cost) bits.push(`<div><strong>Cost:</strong> ${escapeHtml(site.cost)}</div>`); if(site.showers) bits.push(`<div><strong>Showers:</strong> ${escapeHtml(site.showers)}</div>`); if(site.description) bits.push(`<div style="margin-top:8px;">${escapeHtml(site.description)}</div>`); return `<div class="popup-title">${escapeHtml(site.name)}</div><div class="popup-meta">${escapeHtml(site.stateName)} · ${escapeHtml(subtypeLabel(site))}</div>${bits.join('')}<div class="popup-actions"><a href="${nav}" target="_blank" rel="noopener">Navigate</a>${site.website?` <a href="${escapeHtml(site.website)}" target="_blank" rel="noopener">Website</a>`:''}</div>`}
  function clusterPixelSizeForZoom(zoom){if(zoom<=3) return 170; if(zoom<=4) return 145; if(zoom<=5) return 120; if(zoom<=6) return 100; if(zoom<=7) return 82; if(zoom<=8) return 62; if(zoom<=9) return 46; if(zoom<=10) return 34; return 0}
  function aggregateSitesForZoom(sites, zoom){const gridPx=clusterPixelSizeForZoom(zoom); if(!gridPx || !app.map){return {items:sites.map(site=>({kind:'site',site})), gridPx:0};} const buckets=new Map(); sites.forEach(site=>{const p=app.map.project(L.latLng(site.lat,site.lng), zoom); const key=`${Math.floor(p.x/gridPx)}:${Math.floor(p.y/gridPx)}`; if(!buckets.has(key)) buckets.set(key,[]); buckets.get(key).push(site)}); const items=[]; buckets.forEach(bucket=>{if(bucket.length===1){items.push({kind:'site',site:bucket[0]}); return;} const lat=bucket.reduce((s,x)=>s+x.lat,0)/bucket.length; const lng=bucket.reduce((s,x)=>s+x.lng,0)/bucket.length; items.push({kind:'cluster',lat,lng,count:bucket.length,sites:bucket});}); items.sort((a,b)=>(a.kind==='cluster'?0:1)-(b.kind==='cluster'?0:1)); return {items, gridPx};}
  function updateMapReadout(markerCount, zoom, multiplier, gridPx){if(!els.mapReadout) return; const main=els.mapReadout.querySelector('.readout-main'); const mini=els.mapReadout.querySelector('.readout-mini'); if(main) main.textContent=`Zoom ${zoom} · Cluster x${multiplier.toFixed(1)} · Markers ${markerCount}/${app.visibleSites.length}`; const byLayer=countVisibleByFamily(); if(mini) mini.textContent=`Loaded ${app.allSelectedSites.length} · Federal ${byLayer.federal} · State ${byLayer.state} · Local ${byLayer.local} · Private ${byLayer.private} · Boondocking ${byLayer.boondocking} · Info ${byLayer.info}`;}
  function siteMarkerSizeForZoom(zoom){return zoom>=11?30:24}
  function clusterMarkerSize(base, zoom){return zoom>=11?Math.round(base*1.25):base}
  function countVisibleByFamily(){const out={federal:0,state:0,local:0,private:0,boondocking:0,info:0}; app.visibleSites.forEach(site=>{if(out[site.layer]!==undefined) out[site.layer]+=1;}); return out;}
  function renderVisibleSites(shouldFit){if(!app.map || !app.markerGroup) return; app.visibleSites=app.allSelectedSites.filter(passesLayerFilter); app.markerGroup.clearLayers(); const bounds=[]; const zoom=app.map.getZoom(); const agg=aggregateSitesForZoom(app.visibleSites, zoom); const rendered=agg.items; const siteSize=siteMarkerSizeForZoom(zoom); rendered.forEach(item=>{if(item.kind==='site'){const site=item.site; const icon=L.divIcon({className:'',html:`<div class="map-pin ${markerClass(site)}" style="width:${siteSize}px;height:${siteSize}px;">${iconFor(site)}</div>`,iconSize:[siteSize,siteSize],iconAnchor:[siteSize/2,siteSize/2],popupAnchor:[0,-12]}); const marker=L.marker([site.lat,site.lng],{icon,keyboard:false}); marker.bindPopup(popupHtml(site),{maxWidth:320}); marker.addTo(app.markerGroup); bounds.push([site.lat,site.lng]);} else {const base=item.count>=40?40:item.count>=16?36:32; const size=clusterMarkerSize(base, zoom); const icon=L.divIcon({className:'',html:`<div class="map-pin pin-info" style="width:${size}px;height:${size}px;font-weight:700;">${item.count}</div>`,iconSize:[size,size],iconAnchor:[size/2,size/2]}); const marker=L.marker([item.lat,item.lng],{icon,keyboard:false}); marker.on('click',()=>{const clusterBounds=L.latLngBounds(item.sites.map(site=>[site.lat,site.lng])); if(clusterBounds.isValid()){app.map.fitBounds(clusterBounds.pad(0.30),{padding:[40,40],maxZoom:Math.min(zoom+2,12)});} else {app.map.setView([item.lat,item.lng],Math.min(zoom+2,12));}}); marker.bindPopup(`<div class="popup-title">${item.count} sites in this area</div><div class="popup-meta">Click the marker to break the cluster apart.</div>`,{maxWidth:240}); marker.addTo(app.markerGroup); bounds.push([item.lat,item.lng]);}}); if(shouldFit && bounds.length){app.map.fitBounds(bounds,{padding:[32,32]}); app.didInitialFit=true} const markerCount=rendered.length||0; const multiplier=markerCount?app.visibleSites.length/markerCount:1; app.lastRenderInfo={markers:markerCount,multiplier,zoom,grid:agg.gridPx}; updateCounts(); updateMapReadout(markerCount, zoom, multiplier, agg.gridPx); const stateLabel=`${app.enabledStates.size} state${app.enabledStates.size===1?'':'s'}`; els.statusLine.textContent=`${app.visibleSites.length} camping opportunit${app.visibleSites.length===1?'y':'ies'} in ${stateLabel} showing.`; els.dataStats.textContent='';}
  function updateCounts(){}
  async function searchPlaces(){const q=els.searchInput.value.trim(); if(!q) return; els.searchResults.innerHTML='<div class="muted">Searching…</div>'; try{const res=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q='+encodeURIComponent(q),{headers:{Accept:'application/json'}}); const data=await res.json(); if(!Array.isArray(data)||!data.length){els.searchResults.innerHTML='<div class="muted">No results found.</div>'; return;} els.searchResults.innerHTML=data.map((item,idx)=>`<div class="search-result"><div><strong>${escapeHtml(item.display_name)}</strong></div><button class="secondary" data-search-index="${idx}">Go there</button></div>`).join(''); els.searchResults.querySelectorAll('[data-search-index]').forEach(btn=>btn.addEventListener('click',()=>{const item=data[Number(btn.getAttribute('data-search-index'))]; const lat=Number(item.lat),lng=Number(item.lon); app.map.setView([lat,lng],11); if(app.locateMarker) app.map.removeLayer(app.locateMarker); app.locateMarker=L.circleMarker([lat,lng],{radius:8,color:'#d44516',weight:2,fillColor:'#ffd7c9',fillOpacity:.95}).addTo(app.map)}))}catch(err){console.error(err); els.searchResults.innerHTML='<div class="muted">Search failed. Try again in a moment.</div>'}}
  function setDraftPoint(lat,lng){app.draftPoint={lat:+lat.toFixed(6),lng:+lng.toFixed(6)}; els.draftCoords.textContent=`${app.draftPoint.lat}, ${app.draftPoint.lng}`; if(app.draftMarker) app.map.removeLayer(app.draftMarker); const icon=L.divIcon({className:'',html:`<div class="map-pin pin-draft">${svg.draft}</div>`,iconSize:[24,24],iconAnchor:[12,12]}); app.draftMarker=L.marker([lat,lng],{icon}).addTo(app.map)}
  function appendDraftRecord(){if(!app.draftPoint){notify('Drop a draft pin on the map first.'); return;} const rec={name:els.draftName.value.trim()||'Untitled site',category:els.draftCategory.value,state:els.draftState.value.trim().toUpperCase()||'',lat:app.draftPoint.lat,lng:app.draftPoint.lng,website:els.draftWebsite.value.trim(),notes:els.draftNotes.value.trim()}; app.draftQueue.push(JSON.stringify(rec)); localStorage.setItem(STORAGE_KEYS.draftQueue,JSON.stringify(app.draftQueue)); els.draftQueue.value=app.draftQueue.join('\n'); notify('Draft appended to queue.'); els.draftName.value=''; els.draftWebsite.value=''; els.draftNotes.value=''}
  function clearDraftPoint(){app.draftPoint=null; els.draftCoords.textContent='No draft point selected.'; if(app.draftMarker){app.map.removeLayer(app.draftMarker); app.draftMarker=null}}
  function bindEvents(){els.menuToggle.addEventListener('click',()=>els.sidebar.classList.toggle('closed')); els.closeSidebar.addEventListener('click',()=>els.sidebar.classList.add('closed')); els.basemapSelect.addEventListener('change',()=>setBasemap(els.basemapSelect.value)); els.searchBtn.addEventListener('click',searchPlaces); els.searchInput.addEventListener('keydown',e=>{if(e.key==='Enter') searchPlaces()}); els.stateSelect.addEventListener('change', async e=>{const value=e.target.value; app.enabledStates = value==='__ALL__' ? new Set(manifest.states.map(s=>s.code)) : new Set([value]); saveSet(STORAGE_KEYS.enabledStates,app.enabledStates); await refreshData()}); els.layerMenuButton.addEventListener('click',e=>{e.stopPropagation(); const opening=els.layerMenuPanel.hidden; els.layerMenuPanel.hidden=!opening; els.layerMenuButton.setAttribute('aria-expanded', String(opening));}); document.addEventListener('click',e=>{if(!els.layerMenuPanel.hidden && !els.layerMenuPanel.contains(e.target) && !els.layerMenuButton.contains(e.target)){els.layerMenuPanel.hidden=true; els.layerMenuButton.setAttribute('aria-expanded','false');}}); els.layerQuickFilters.querySelectorAll('[data-layer-toggle-group]').forEach(btn=>btn.addEventListener('click',()=>toggleLayerGroup(btn.getAttribute('data-layer-toggle-group')))); els.appendDraftBtn.addEventListener('click',appendDraftRecord); els.clearDraftBtn.addEventListener('click',clearDraftPoint); els.copyQueueBtn.addEventListener('click', async()=>{try{await navigator.clipboard.writeText(els.draftQueue.value); notify('Queue copied to clipboard.')}catch{notify('Clipboard copy failed.',3200)}}); els.clearQueueBtn.addEventListener('click',()=>{app.draftQueue=[]; localStorage.setItem(STORAGE_KEYS.draftQueue,JSON.stringify(app.draftQueue)); els.draftQueue.value=''; notify('Queue cleared.')}); app.map.on('zoomend',()=>renderVisibleSites(false))}
  initMap(); buildStateSelect(); buildLayerControls(); bindEvents(); refreshData();
})();