create table if not exists public.monthly_media_schedule (
  id bigint generated by default as identity primary key,
  series_title text not null,
  last_scheduled_date date,
  record_time text,
  record_source text,
  schedule_pattern text,
  last_episode_scheduled integer,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists monthly_media_schedule_title_idx
  on public.monthly_media_schedule (lower(series_title));

create index if not exists monthly_media_schedule_active_idx
  on public.monthly_media_schedule (is_active, lower(series_title));

comment on table public.monthly_media_schedule is
  'Series that require manual monthly media scheduling and recording updates.';

comment on column public.monthly_media_schedule.last_episode_scheduled is
  'Most recent episode number set to record for the series.';

create table if not exists public.holiday_observances (
  id bigint generated by default as identity primary key,
  title text not null,
  rule_type text not null check (rule_type in (
    'fixed_date',
    'nth_weekday',
    'last_weekday',
    'month_scope',
    'date_range_fixed',
    'manual_text'
  )),
  month smallint,
  rule_month smallint,
  day smallint,
  nth smallint,
  weekday smallint,
  start_month smallint,
  start_day smallint,
  end_month smallint,
  end_day smallint,
  manual_date_text text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint holiday_observances_month_chk check (month is null or month between 1 and 12),
  constraint holiday_observances_rule_month_chk check (rule_month is null or rule_month between 1 and 12),
  constraint holiday_observances_day_chk check (day is null or day between 1 and 31),
  constraint holiday_observances_nth_chk check (nth is null or nth between 1 and 5),
  constraint holiday_observances_weekday_chk check (weekday is null or weekday between 0 and 6),
  constraint holiday_observances_start_month_chk check (start_month is null or start_month between 1 and 12),
  constraint holiday_observances_start_day_chk check (start_day is null or start_day between 1 and 31),
  constraint holiday_observances_end_month_chk check (end_month is null or end_month between 1 and 12),
  constraint holiday_observances_end_day_chk check (end_day is null or end_day between 1 and 31)
);

create index if not exists holiday_observances_month_idx
  on public.holiday_observances (coalesce(month, rule_month, start_month), lower(title));

comment on table public.holiday_observances is
  'Custom recurring holidays and observances used by the WNMU calendar page.';

comment on column public.holiday_observances.rule_type is
  'How the yearly date should be calculated: fixed_date, nth_weekday, last_weekday, month_scope, date_range_fixed, or manual_text.';
